apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qloapps
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: qloapps
    spec:
      containers:
      - name: qloapps
        image: alejandrolmeida.azurecr.io/qloapps:v1
        ports:
          - containerPort: 80
            name: http
          - containerPort: 3306
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: qloapps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 3306
      name: mysql  
  selector:
    app: qloapps