---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: core2mvc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: core2mvc
    spec:
      containers:
      - name: core2mvc
        image: alejandrolmeida.azurecr.io/core2mvc:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 1m
---
kind: Service
apiVersion: v1
metadata:
  name: core2mvc-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: core2mvc
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: core2mvc-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: core2mvc-deployment
  minReplicas: 20
  maxReplicas: 40
  targetCPUUtilizationPercentage: 20