version: '3.4'

services:
  selfie.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=ngrok
    ports:
      - "80:80"

  selfie.backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  azurebrains.storage.valetkey:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:80"

  mssql:
    ports:
      - "1433:1433"

  azurite:
    ports:
      - "10000-10002:10000-10002"