---
kind: Secret
apiVersion: v1
metadata:
  name: sqlsecret
type: Opaque
data: 
  sapassword: UGFzc3dvcmQxMjM0
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  kind: Managed
reclaimPolicy: Retain
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "sqldb-pv"
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-disk"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: sqlserverstatefulset
spec:
  serviceName: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: alejandrolmeida.azurecr.io/selfiemssql:v2
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlsecret
                  key: sapassword
          volumeMounts:
            - name: sqldb-home
              mountPath: /var/opt
              
      volumes:
      - name: sqldb-home
        persistentVolumeClaim:
          claimName: sqldb-pv
---
kind: Service
apiVersion: v1
metadata:
  name: mssql
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: mssql
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    app: mssql          

          