---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: selfiefrontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selfiefrontend
    spec:
      containers:
      - name: selfiefrontend
        image: alejandrolmeida.azurecr.io/selfiefrontend:v5
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1m
---
kind: Service
apiVersion: v1
metadata:
  name: selfiefrontend-service
spec:
  loadBalancerIP: 52.179.102.158
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: selfiefrontend
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: selfiefrontend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: selfiefrontend-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60