version: '3.4'
services:
  selfie.frontend:
    image: selfiefrontend
    build:
      context: ./source
      dockerfile: ./Selfie.Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=ngrok
    ports:
     - "80:80"

  selfie.backend:
    image: selfiebackend
    build:
      context: ./source
      dockerfile: ./Selfie.Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "5000:80"

  azurebrains.storage.valetkey:
    image: storagevaletkey
    build:
      context: ./source
      dockerfile: ./Azurebrains.Storage.ValetKey/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
     - "5001:80"

  mssql:
    image: alejandrolmeida.azurecr.io/selfiemssql:v2
    environment:
      - 'SA_PASSWORD=Password1234'
      - 'ACCEPT_EULA=Y'
    ports:
     - "1433:1433"

  azurite:
    image: alejandrolmeida.azurecr.io/azurite:v1
    ports:
     - "10000-10002:10000-10002"
